### ISSUE TITLE
make avaiable in component

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [OXOYO/X-Browser-Update-Vue#1]
Can you please make it usable like this

//Home.vue
import XBrowserUpdate from 'x-browser-update'

export default {
   components: {
       XBrowserUpdate
   }
}

I tried but got:  Failed to mount component: template or render function not defined.

**Comment by OXOYO** [comment]
It's a plug-in, and more detailed informations at https://vuejs.org/v2/guide/plugins.html

So, the way you use it is not correct, it should be the following
## main.js
```bash
import XBrowserUpdate from 'x-browser-update'

// Use plugins by calling the Vue.use() global method:
Vue.use(XBrowserUpdate)
```
## App.vue
```bash
<template>
  <div id="app" class="layout">
    <x-browser-update :config="browserUpdateConfig"></x-browser-update>
  </div>
</template>

<script>
  export default {
    name: 'app',
    data () {
      return {
        browserUpdateConfig: {
          ...
        }
      }
    }
  }
</script>
```

**Comment by diego-lipinski-de-castro** [comment]
oh okay, my bad, so distracted did not even noticed, i'm retarded, sorry
